version: '3.9'

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql_api_crud
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'db_api_crud'

    ports:
      - '3306:3306'
